// ── Worldbuilding Vocabulary Dictionaries ──────────────────────────────────────

// Over 300 Adjectives for dramatic, deep worldbuilding
export const ADJECTIVES = [
  'Abyssal', 'Adamant', 'Amber', 'Ancient', 'Arcane', 'Ashen', 'Astral', 'Aurelian', 'Autumn', 'Azure',
  'Battered', 'Binding', 'Bitter', 'Black', 'Blazing', 'Bleeding', 'Blessed', 'Blighted', 'Blind', 'Bloodied',
  'Blue', 'Bone', 'Bound', 'Brazen', 'Breaking', 'Bright', 'Broken', 'Bronze', 'Brooding', 'Burning',
  'Callous', 'Celestial', 'Chained', 'Chilling', 'Cinder', 'Clouded', 'Cold', 'Copper', 'Corrupted', 'Crimson',
  'Crumbling', 'Crying', 'Crystal', 'Cunning', 'Cursed', 'Dancing', 'Dark', 'Dawn', 'Dead', 'Decayed',
  'Deep', 'Defiant', 'Desolate', 'Diamond', 'Dim', 'Dire', 'Distant', 'Divine', 'Dormant', 'Dread',
  'Dreaming', 'Drowning', 'Drowned', 'Dull', 'Dusk', 'Dusty', 'Dying', 'Earthen', 'Ebony', 'Echoing',
  'Eldritch', 'Ember', 'Emerald', 'Empty', 'Enchanted', 'Endless', 'Enduring', 'Enigmatic', 'Eternal', 'Ethereal',
  'Exiled', 'Fading', 'Faint', 'Fair', 'Fallen', 'False', 'Feral', 'Fierce', 'Fiery', 'Final',
  'First', 'Flaming', 'Flashing', 'Flickering', 'Floating', 'Flooded', 'Flying', 'Forbidden', 'Forgotten', 'Forsaken',
  'Foul', 'Fractured', 'Free', 'Freezing', 'Frost', 'Frozen', 'Ghostly', 'Gilded', 'Glacial', 'Gleaming',
  'Gloom', 'Glorious', 'Golden', 'Grand', 'Grave', 'Great', 'Green', 'Grey', 'Grim', 'Grizzled',
  'Hallowed', 'Hanging', 'Haunted', 'Heavenly', 'Heavy', 'Hidden', 'High', 'Hollow', 'Holy', 'Honored',
  'Horned', 'Howling', 'Humble', 'Hungry', 'Icy', 'Idle', 'Illuminated', 'Immortal', 'Imperial', 'Infernal',
  'Infinite', 'Invisible', 'Iron', 'Ivory', 'Jade', 'Jagged', 'Joyous', 'Keen', 'Last', 'Laughing',
  'Leaden', 'Light', 'Living', 'Lone', 'Lonely', 'Long', 'Lost', 'Low', 'Luminous', 'Lunar',
  'Lurking', 'Mad', 'Magic', 'Majestic', 'Marble', 'Masked', 'Melancholy', 'Mended', 'Merciless', 'Mighty',
  'Mirthful', 'Misted', 'Misty', 'Mocking', 'Moonlit', 'Mortal', 'Mossy', 'Mourning', 'Muddy', 'Mute',
  'Mystic', 'Naked', 'Nameless', 'Narrow', 'New', 'Night', 'Noble', 'Northern', 'Oaken', 'Obsidian',
  'Ocean', 'Old', 'Onyx', 'Opal', 'Open', 'Orphaned', 'Overgrown', 'Painted', 'Pale', 'Patient',
  'Pearl', 'Perfect', 'Phantom', 'Piercing', 'Pious', 'Pitted', 'Plagued', 'Plain', 'Poisoned', 'Primal',
  'Primeval', 'Primordial', 'Proud', 'Pure', 'Quiet', 'Radiant', 'Raging', 'Rampant', 'Ravaged', 'Ravenous',
  'Red', 'Relentless', 'Restless', 'Revered', 'Righteous', 'Risen', 'Roaring', 'Rough', 'Ruby', 'Ruined',
  'Rusted', 'Sacred', 'Sad', 'Salt', 'Sapphire', 'Savage', 'Scarlet', 'Scarred', 'Scorched', 'Screaming',
  'Sea', 'Sealed', 'Secret', 'Serrated', 'Shadowed', 'Shadowy', 'Shattered', 'Shifting', 'Shining', 'Shivering',
  'Short', 'Shrouded', 'Silent', 'Silver', 'Singing', 'Sinking', 'Skeletal', 'Sleeping', 'Slumbering', 'Small',
  'Smoldering', 'Smooth', 'Solar', 'Solemn', 'Solid', 'Solitary', 'Sorrowful', 'Southern', 'Sparkling', 'Spectral',
  'Spiked', 'Spinning', 'Spiteful', 'Splendid', 'Spring', 'Stained', 'Star', 'Starry', 'Starving', 'Steadfast',
  'Steel', 'Still', 'Stolen', 'Stone', 'Storm', 'Stormy', 'Strange', 'Sublime', 'Summer', 'Sundered',
  'Sunken', 'Sunlit', 'Sweet', 'Swift', 'Tall', 'Tarnished', 'Tattered', 'Tearful', 'Thick', 'Thin',
  'Thorned', 'Thundering', 'Timeless', 'Tired', 'Topaz', 'Torn', 'Tranquil', 'Treachorous', 'True', 'Twilight',
  'Twisted', 'Unbeaten', 'Unbound', 'Unbroken', 'Uncharted', 'Undying', 'Unending', 'Unforgiven', 'Unknown', 'Unseen',
  'Unspoken', 'Untamed', 'Valiant', 'Vanished', 'Veiled', 'Velvet', 'Vengeful', 'Vigilant', 'Violent', 'Violet',
  'Void', 'Wailing', 'Wakeful', 'Wandering', 'Waning', 'Warm', 'Warped', 'Wasted', 'Watchful', 'Watery',
  'Waxing', 'Wayward', 'Weathered', 'Weeping', 'Whispering', 'White', 'Wicked', 'Wide', 'Wild', 'Windy',
  'Winged', 'Winter', 'Withered', 'Wooden', 'Worn', 'Wrathful', 'Wretched', 'Yellow', 'Young', 'Zealous'
];

// Over 300 Nouns for places, items, factions, lore
export const NOUNS = [
  'Abyss', 'Accord', 'Aegis', 'Age', 'Altar', 'Amulet', 'Anchor', 'Anvil', 'Arch', 'Archer',
  'Archway', 'Arm', 'Armor', 'Arrow', 'Ash', 'Ashes', 'Aura', 'Avatar', 'Axe', 'Bane',
  'Bank', 'Banner', 'Barrow', 'Basin', 'Bastion', 'Battle', 'Bay', 'Beacon', 'Beak', 'Bear',
  'Beast', 'Bell', 'Belly', 'Belt', 'Binding', 'Birch', 'Bird', 'Blade', 'Blight', 'Blood',
  'Blossom', 'Bluff', 'Boar', 'Bone', 'Book', 'Boon', 'Boots', 'Bough', 'Bow', 'Bowl',
  'Branch', 'Brass', 'Breach', 'Breath', 'Breeze', 'Briar', 'Bridge', 'Brimstone', 'Brook', 'Brother',
  'Brotherhood', 'Bull', 'Cairn', 'Call', 'Caller', 'Canyon', 'Cape', 'Captain', 'Castle', 'Cat',
  'Catacombs', 'Cavern', 'Chain', 'Chalice', 'Champion', 'Chant', 'Chaos', 'Chapel', 'Chapter', 'Chasm',
  'Child', 'Children', 'Choir', 'Chronicle', 'Cinder', 'Circle', 'Citadel', 'City', 'Clan', 'Claw',
  'Cliff', 'Cloak', 'Clock', 'Cloud', 'Coast', 'Coin', 'Cold', 'Collar', 'Company', 'Compass',
  'Conclave', 'Cortex', 'Council', 'Court', 'Covenant', 'Cove', 'Crab', 'Crag', 'Crater', 'Creek',
  'Crest', 'Crevasse', 'Crier', 'Cross', 'Crossing', 'Crown', 'Crypt', 'Crystal', 'Cult', 'Cup',
  'Curse', 'Dagger', 'Dark', 'Daughter', 'Dawn', 'Day', 'Death', 'Decree', 'Deep', 'Deer',
  'Demon', 'Den', 'Depth', 'Desert', 'Desire', 'Destiny', 'Devil', 'Dew', 'Diamond', 'Dirge',
  'Disc', 'Divide', 'Dog', 'Domain', 'Dominion', 'Doom', 'Door', 'Dove', 'Dragon', 'Dream',
  'Drift', 'Drop', 'Dune', 'Dungeon', 'Dusk', 'Dust', 'Eagle', 'Earth', 'Echo', 'Eclipse',
  'Edge', 'Edict', 'Eel', 'Egg', 'Element', 'Elephant', 'Elm', 'Ember', 'Embrace', 'Emerald',
  'Emperor', 'Empire', 'Enclave', 'End', 'Enemy', 'Engine', 'Enigma', 'Entity', 'Era', 'Essence',
  'Estate', 'Exarch', 'Exile', 'Expanse', 'Eye', 'Face', 'Fall', 'Falls', 'Fang', 'Fate',
  'Father', 'Fault', 'Feather', 'Fellowship', 'Fen', 'Field', 'Fiend', 'Finger', 'Fire', 'Fish',
  'Fist', 'Flame', 'Flask', 'Flock', 'Flood', 'Flower', 'Flute', 'Fog', 'Fold', 'Folly',
  'Fool', 'Foot', 'Ford', 'Forest', 'Forge', 'Fort', 'Fortress', 'Fortune', 'Fox', 'Fracture',
  'Friend', 'Frost', 'Fruit', 'Fury', 'Gale', 'Gap', 'Garden', 'Gargoyle', 'Gate', 'Gathering',
  'Gauntlet', 'Gem', 'Ghost', 'Giant', 'Gift', 'Glaive', 'Glass', 'Glen', 'Glory', 'Glove',
  'Goat', 'God', 'Goddess', 'Gold', 'Gorge', 'Grace', 'Grasp', 'Grave', 'Grief', 'Griffon',
  'Grove', 'Guard', 'Guardian', 'Guild', 'Gulf', 'Gull', 'Hail', 'Hair', 'Halberd', 'Hall',
  'Halo', 'Hammer', 'Hand', 'Harbor', 'Hare', 'Harp', 'Harvest', 'Hatchet', 'Haven', 'Hawk',
  'Head', 'Heart', 'Hearth', 'Heath', 'Heaven', 'Heir', 'Hell', 'Helm', 'Herald', 'Hero',
  'Hide', 'Hill', 'Hold', 'Hollow', 'Holt', 'Home', 'Honor', 'Hood', 'Hook', 'Hope',
  'Horde', 'Horn', 'Horse', 'Hound', 'Hour', 'House', 'Hunter', 'Hymn', 'Ice', 'Illusion',
  'Image', 'Incantation', 'Inferno', 'Iron', 'Island', 'Isle', 'Ivy', 'Jackal', 'Jade', 'Jaw',
  'Jewel', 'Journey', 'Judge', 'Justice', 'Keep', 'Keeper', 'Key', 'King', 'Kingdom', 'Kiss',
  'Knight', 'Knot', 'Labyrinth', 'Lake', 'Lament', 'Lamp', 'Lance', 'Land', 'Lantern', 'Lark',
  'Law', 'League', 'Leaf', 'Legacy', 'Legion', 'Library', 'Lie', 'Light', 'Lightning', 'Lily',
  'Lion', 'Lip', 'Lock', 'Locket', 'Lodge', 'Lord', 'Lore', 'Lotus', 'Love', 'Lover',
  'Lute', 'Mace', 'Machine', 'Mage', 'Magic', 'Magister', 'Maiden', 'Mantle', 'March', 'Mark',
  'Marsh', 'Martyr', 'Mask', 'Massacre', 'Master', 'Maw', 'Maze', 'Meadow', 'Memory', 'Mercy',
  'Message', 'Messenger', 'Metal', 'Mind', 'Mine', 'Mire', 'Mirror', 'Mist', 'Monk', 'Monkey',
  'Monster', 'Monument', 'Moon', 'Moor', 'Morning', 'Mortal', 'Moss', 'Moth', 'Mother', 'Mountain',
  'Mourner', 'Mouth', 'Mud', 'Muse', 'Mystery', 'Myth', 'Nail', 'Name', 'Nation', 'Nature',
  'Necklace', 'Needle', 'Nest', 'Net', 'Night', 'Nightingale', 'Nightmare', 'Node', 'Noose', 'North',
  'Note', 'Oak', 'Oar', 'Oath', 'Obelisk', 'Observatory', 'Ocean', 'Oculus', 'Offering', 'Omen',
  'Onyx', 'Opal', 'Oracle', 'Orb', 'Order', 'Ore', 'Outpost', 'Owl', 'Pact', 'Page',
  'Pain', 'Palace', 'Palm', 'Panther', 'Parchment', 'Pass', 'Passage', 'Pasture', 'Path', 'Patriarch',
  'Pawn', 'Peace', 'Peak', 'Pearl', 'Pendant', 'Peninsula', 'Petal', 'Phantom', 'Phoenix', 'Pick',
  'Pike', 'Pillar', 'Pin', 'Pine', 'Pinnacle', 'Pipe', 'Pit', 'Plague', 'Plain', 'Plateau',
  'Pledge', 'Point', 'Poison', 'Pond', 'Pool', 'Port', 'Portal', 'Pouch', 'Power', 'Prayer',
  'Pride', 'Priest', 'Priestess', 'Prince', 'Princess', 'Prison', 'Promise', 'Prophecy', 'Prophet', 'Purge',
  'Pyramid', 'Pyre', 'Quarry', 'Queen', 'Quest', 'Quill', 'Quiver', 'Rain', 'Rat', 'Raven',
  'Ravine', 'Reach', 'Reaches', 'Realm', 'Reaper', 'Rebel', 'Reckoning', 'Record', 'Refuge', 'Relic',
  'Requiem', 'Rest', 'Return', 'Revelation', 'Revenge', 'Rib', 'Riddle', 'Ridge', 'Rift', 'Ring',
  'Rite', 'Ritual', 'River', 'Road', 'Roar', 'Robe', 'Rock', 'Rod', 'Rogue', 'Root',
  'Rope', 'Rose', 'Ruin', 'Rule', 'Ruler', 'Rune', 'Sacrifice', 'Sage', 'Sail', 'Saint',
  'Salt', 'Sanctuary', 'Sand', 'Sash', 'Savant', 'Savior', 'Scale', 'Scar', 'Scepter', 'Scholar',
  'Scimitar', 'Scroll', 'Scythe', 'Sea', 'Seal', 'Seat', 'Secret', 'Sect', 'Seed', 'Seer',
  'Sentinel', 'Serpent', 'Servant', 'Shadow', 'Shaft', 'Shale', 'Shard', 'Shark', 'Sheath', 'Sheep',
  'Shell', 'Shield', 'Ship', 'Shoal', 'Shore', 'Shrine', 'Shroud', 'Sickle', 'Siege', 'Sigil',
  'Sign', 'Silence', 'Silk', 'Silver', 'Sin', 'Singer', 'Sister', 'Sisterhood', 'Skeleton', 'Skin',
  'Skull', 'Sky', 'Slate', 'Slave', 'Slayer', 'Sleep', 'Sleeper', 'Slope', 'Smoke', 'Snake',
  'Snow', 'Society', 'Soldier', 'Son', 'Song', 'Sorrow', 'Soul', 'Sound', 'South', 'Spark',
  'Sparrow', 'Spear', 'Spell', 'Spider', 'Spine', 'Spire', 'Spirit', 'Sponge', 'Spore', 'Spring',
  'Spur', 'Spy', 'Staff', 'Stag', 'Star', 'State', 'Statue', 'Steel', 'Step', 'Steppe',
  'Stone', 'Storm', 'Strand', 'Stranger', 'Stream', 'Street', 'Strike', 'String', 'Sultan', 'Summer',
  'Sun', 'Swamp', 'Swan', 'Sword', 'Symbol', 'Syndicate', 'Tale', 'Talisman', 'Talon', 'Tangle',
  'Tear', 'Teeth', 'Temple', 'Terror', 'Testament', 'Thief', 'Thistle', 'Thorn', 'Thread', 'Throne',
  'Thunder', 'Tide', 'Tiger', 'Timber', 'Time', 'Titan', 'Toad', 'Tomb', 'Tome', 'Tooth',
  'Torch', 'Tower', 'Town', 'Trail', 'Traitor', 'Tree', 'Trial', 'Tribe', 'Trident', 'Trinity',
  'Truth', 'Tundra', 'Tunnel', 'Twin', 'Tyrant', 'Union', 'Urn', 'Vale', 'Valley', 'Vampire',
  'Vanguard', 'Vassal', 'Vault', 'Veil', 'Vein', 'Vengeance', 'Venom', 'Vessel', 'Vestige', 'Vial',
  'Vice', 'Victor', 'View', 'Vigil', 'Village', 'Vine', 'Viper', 'Vision', 'Voice', 'Void',
  'Vow', 'Voyage', 'Vulture', 'Wail', 'Wall', 'Wand', 'War', 'Warband', 'Ward', 'Warden',
  'Warlock', 'Warlord', 'Warrior', 'Waste', 'Watch', 'Watcher', 'Water', 'Wave', 'Way', 'Weapon',
  'Weaver', 'Web', 'Well', 'West', 'Wheel', 'Whip', 'Whisper', 'Widow', 'Wife', 'Wild',
  'Will', 'Willow', 'Wind', 'Window', 'Wing', 'Winter', 'Wish', 'Witch', 'Wolf', 'Wood',
  'Word', 'World', 'Worm', 'Wound', 'Wraith', 'Wrath', 'Wreath', 'Wyrm', 'Yarn', 'Year',
  'Yew', 'Youth', 'Zealot', 'Zenith', 'Zephyr'
];

export const TOWN_PREFIXES = ['Upper ', 'Lower ', 'East ', 'West ', 'North ', 'South ', 'Great ', 'Little ', 'Old ', 'New ', 'Fort ', 'Port ', 'Mount ', 'Lake ', 'Camp '];
export const TOWN_SUFFIXES = [
  'barrow', 'beach', 'beck', 'bend', 'berg', 'borough', 'bourne', 'bridge', 'brook', 'burn', 'bury', 'by', 'cairn', 'camp', 'cliff',
  'combe', 'cove', 'crag', 'crest', 'croft', 'cross', 'dale', 'dell', 'den', 'dike', 'ditch', 'don', 'down', 'drift', 'dun',
  'edge', 'end', 'fall', 'falls', 'farm', 'fell', 'fen', 'field', 'fold', 'ford', 'fork', 'fort', 'gap', 'gate', 'gill',
  'glen', 'grad', 'green', 'grove', 'guard', 'hall', 'ham', 'haven', 'heath', 'hill', 'hold', 'hollow', 'holm', 'holt', 'home',
  'hood', 'hope', 'hurst', 'ing', 'keep', 'lake', 'land', 'landing', 'lea', 'lock', 'mark', 'mead', 'mere', 'mill', 'moor',
  'more', 'mount', 'mouth', 'nest', 'peak', 'point', 'pool', 'port', 'post', 'reach', 'rest', 'ridge', 'rise', 'rock', 'run',
  'seat', 'shaw', 'shire', 'shore', 'side', 'slip', 'spring', 'stead', 'stone', 'strand', 'stream', 'thorpe', 'ton', 'town', 'vale',
  'valley', 'view', 'ville', 'wall', 'ward', 'watch', 'water', 'way', 'well', 'wick', 'wood', 'worth', 'yard'
];

export const TAVERN_NOUNS = [
  'Axe', 'Badger', 'Barrel', 'Bear', 'Bell', 'Boar', 'Boat', 'Boot', 'Bottle', 'Bow', 'Bowl', 'Bull',
  'Candle', 'Cat', 'Chalice', 'Cask', 'Cockerel', 'Coin', 'Compass', 'Copper', 'Crow', 'Crown', 'Cup',
  'Dagger', 'Deer', 'Dog', 'Dragon', 'Eagle', 'Elephant', 'Eye', 'Feather', 'Fish', 'Flask', 'Flute', 'Fox',
  'Frog', 'Ghost', 'Giant', 'Goat', 'Goblet', 'Gold', 'Goose', 'Griffon', 'Hammer', 'Hare', 'Harp', 'Hart',
  'Hawk', 'Helm', 'Horn', 'Horse', 'Hound', 'Inn', 'Jester', 'Jug', 'Keg', 'Key', 'King', 'Knight', 'Lantern',
  'Lion', 'Lute', 'Maiden', 'Mermaid', 'Monkey', 'Moon', 'Mug', 'Mule', 'Oak', 'Owl', 'Ox', 'Pig',
  'Pint', 'Pipe', 'Plow', 'Pony', 'Pot', 'Prince', 'Queen', 'Ram', 'Rat', 'Raven', 'Rooster', 'Rose',
  'Sail', 'Serpent', 'Shield', 'Ship', 'Silver', 'Skull', 'Snake', 'Spade', 'Stag', 'Star', 'Stone',
  'Sun', 'Swan', 'Sword', 'Tankard', 'Thistle', 'Toad', 'Tree', 'Trout', 'Unicorn', 'Vine', 'Wand', 'Wheel',
  'Whistle', 'Wolf', 'Wyrm', 'Yew'
];

export const SHIP_ADJECTIVES = [
  'Audacious', 'Black', 'Bloody', 'Brave', 'Crimson', 'Dancing', 'Dark', 'Dauntless', 'Defiant',
  'Drowned', 'Drunken', 'Fair', 'Fallen', 'Fearless', 'Flying', 'Golden', 'Grim', 'Howling',
  'Iron', 'Jolly', 'Laughing', 'Lone', 'Lucky', 'Mad', 'Mighty', 'Painted', 'Pale', 'Proud',
  'Red', 'Restless', 'Roaring', 'Rogue', 'Royal', 'Salty', 'Savage', 'Sea', 'Shadow', 'Silent',
  'Silver', 'Sinking', 'Storm', 'Swift', 'Unbound', 'Vengeful', 'Wandering', 'Weeping', 'White', 'Wild'
];

export const SHIP_NOUNS = [
  'Albatross', 'Arrow', 'Banshee', 'Barnacle', 'Barque', 'Beauty', 'Bounty', 'Breeze', 'Clipper',
  'Cloud', 'Corsair', 'Crest', 'Cutlass', 'Dagger', 'Dart', 'Dawn', 'Demon', 'Devil', 'Dog',
  'Dolphin', 'Dragon', 'Drake', 'Dream', 'Drifter', 'Eagle', 'Eel', 'Empress', 'Endeavour',
  'Falcon', 'Fancy', 'Fortune', 'Fox', 'Fury', 'Galleon', 'Ghost', 'Gull', 'Hawk', 'Heart',
  'Hope', 'Horizon', 'Hound', 'Hunter', 'Jackal', 'Jewel', 'Kestrel', 'King', 'Kraken', 'Lady',
  'Leviathan', 'Lion', 'Maiden', 'Marauder', 'Mermaid', 'Monarch', 'Moon', 'Pearl', 'Pelican',
  'Petrel', 'Phantom', 'Pillager', 'Plunderer', 'Princess', 'Prowler', 'Queen', 'Racer', 'Raider',
  'Ranger', 'Raven', 'Reaper', 'Revenge', 'Rider', 'Rose', 'Rover', 'Sabre', 'Schooner', 'Sea',
  'Seagull', 'Serpent', 'Shadow', 'Shark', 'Siren', 'Skimmer', 'Skull', 'Sloop', 'Song', 'Spear',
  'Spectre', 'Spirit', 'Squid', 'Star', 'Storm', 'Striker', 'Sun', 'Swallow', 'Swan', 'Sword',
  'Talon', 'Tempest', 'Terror', 'Tide', 'Tiger', 'Trident', 'Vagabond', 'Valyrie', 'Vanguard',
  'Vengeance', 'Venture', 'Vessel', 'Victory', 'Viper', 'Voyager', 'Wake', 'Wanderer', 'Wave',
  'Whale', 'Wind', 'Wing', 'Wolf', 'Wraith', 'Wyrm'
];

export const DEITY_DOMAINS = [
  'the Harvest', 'the Forge', 'the Sea', 'the Sky', 'the Underworld', 'the Hunt', 'the Hearth',
  'the Moon', 'the Sun', 'the Stars', 'the Crossroads', 'the Dead', 'the Living', 'the Wilds',
  'the Deep', 'the Depths', 'the Void', 'the Abyss', 'the Storm', 'the Wind', 'the Rain',
  'the Flame', 'the Fire', 'the Ash', 'the Earth', 'the Mountain', 'the River', 'the Forest',
  'the Wood', 'the Grove', 'the Seasons', 'the Spring', 'the Summer', 'the Autumn', 'the Winter',
  'the Day', 'the Night', 'the Dawn', 'the Dusk', 'the Twilight', 'the Shadows', 'the Light',
  'the Dark', 'the Blind', 'the Seeing', 'the Forgotten', 'the Lost', 'the Found', 'the Broken',
  'the Mended', 'the Fallen', 'the Risen', 'the Blood', 'the Bone', 'the Flesh', 'the Mind',
  'the Soul', 'the Spirit', 'the Dream', 'the Nightmare', 'the Waking', 'the Sleep', 'the Grave',
  'the Tomb', 'the Cradle', 'the Sword', 'the Shield', 'the Bow', 'the Spear', 'the Axe',
  'the Hammer', 'the Anvil', 'the Loom', 'the Wheel', 'the Path', 'the Road', 'the Journey',
  'the Destination', 'the Beginning', 'the End', 'the Alpha', 'the Omega', 'the First', 'the Last',
  'the Hidden', 'the Revealed', 'the Secret', 'the Truth', 'the Lie', 'the Whisper', 'the Scream',
  'the Song', 'the Silence', 'the Dance', 'the Stillness', 'the Word', 'the Deed', 'the Thought',
  'the Memory', 'the Prophecy', 'the Fate', 'the Destiny', 'the Chance', 'the Luck', 'the Fortune',
  'the Misfortune', 'the Blessing', 'the Curse', 'the Gift', 'the Toll', 'the Price', 'the Debt',
  'the Reward', 'the Punishment', 'the Justice', 'the Vengeance', 'the Mercy', 'the Wrath'
];
